services:
  frontend:
    build:
      context: ./telemedicine-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_PY_API_URL=http://api:5001 
    depends_on:
      - api
    networks:
      - app-network
    volumes:
      - ./telemedicine-frontend:/app
      - /app/node_modules  # Prevents overwriting node_modules
    restart: always

  backend:
    build:
      context: ./telemedicine-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./telemedicine-backend:/app
      - /app/node_modules  # Prevents overwriting node_modules
    networks:
      - app-network
    restart: always
    depends_on:
      - api # Ensures the Flask API is ready before the Node.js backend starts

  api:
    build:
      context: ./telemedicine-backend/api/ml_model
      dockerfile: Dockerfile
    ports:
      - "5001:5001" 
    networks:
      - app-network
    volumes:
      - ./telemedicine-backend/api/ml_model:/app
    restart: always

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    networks:
      - app-network

volumes:
  ollama_data:

networks:
  app-network:
    driver: bridge
